### ISSUE TITLE
Broken link on the page for the documentation

### ISSUE THREAD

**Issue by hammadhaleem** [diydrones/droneapi-python#21]
Follow me & Hello world example links appears broken. I cannot view the examples.

**Comment by mrpollo** [comment]
thanks for noticing!, I'm about to fix those links, meanwhile you can access them here https://github.com/diydrones/droneapi-python/tree/master/example

**Comment by geeksville** [comment]
thanks Ramon!

**Comment by hammadhaleem** [comment]
Thanks for those links :)

On Fri, Jan 16, 2015 at 3:32 AM, Kevin Hester <notifications@github.com>
wrote:

> thanks Ramon!
>
> On Thu Jan 15 2015 at 9:02:20 AM Ramon Roche <notifications@github.com>
> wrote:
>
> > thanks for noticing!, I'm about to fix those links, meanwhile you can
> > access them here
> > https://github.com/diydrones/droneapi-python/tree/master/example
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/diydrones/droneapi-python/issues/21#issuecomment-70119651>
>
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/droneapi-python/issues/21#issuecomment-70146463>
> .
>



-- 
Regards
Hammad Haleem
